### ISSUE TITLE
Couldn't install package when Nova was installed via .zip file

### ISSUE THREAD

**Issue by davybaccaert** [Sparclex/nova-creatable-belongs-to#4]
I had the Nova package installed via .zip file and could not install this package.
Reason i presume was that this package requires a ^1.2 version of Nova and the 
.zip install sets the nova version to "*".

Once i undid the .zip install, and followed docs on an installation via composer (with the
needed changes in composer.json) i was able to install this package.

**Comment by Sparclex** [comment]
What was the error message?

**Comment by Sparclex** [comment]
No response
