### ISSUE TITLE
How do we handle other fields?

### ISSUE THREAD

**Issue by RyanPaiva56** [Sparclex/nova-creatable-belongs-to#5]
What happens if I want to create a "city" but I need to pass a state value to create the city?

Right now I'm using this package...

https://novapackages.com/packages/dillingham/nova-ajax-select

...to show a list of cities based on the state they select. If they don't find the city they're looking for, it would be great to create it but I don't think I can with your package without sending some additional required data to finish the job. Any help would be appreciated.

**Comment by Sparclex** [comment]
Yes this is not possible. The package is only for resources which only require one column. All additional columns may be edited afterwards.
